extra_fn_clean_exts:
    - '.align_summary'
    - '.R1'
    - '.accepted_hits'

# Favourite modules that should appear at the top in preference
# This is in addition to those below. These appear above _all_ other
# modules (even those not present in the below list).
top_modules: []
