theme: jekyll-theme-slate
title: TM3'seq
description: Tagmentation-Mediated 3'-enriched RNA-seq
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
